// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tv7Playlist.Data;

namespace Tv7Playlist.Data.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    [Migration("20181209233600_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("Tv7Playlist.Data.PlaylistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("TrackNumber");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasAlternateKey("TrackNumber");

                    b.ToTable("PlaylistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
