// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tv7Playlist.Data;

namespace Tv7Playlist.Data.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    [Migration("20190130214707_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Tv7Playlist.Data.PlaylistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChannelNumberExport");

                    b.Property<int>("ChannelNumberImport");

                    b.Property<DateTime>("Created");

                    b.Property<string>("EpgMatchName");

                    b.Property<bool>("IsAvailable");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("LogoUrl");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<int>("Position");

                    b.Property<string>("UrlOriginal");

                    b.Property<string>("UrlProxy");

                    b.HasKey("Id");

                    b.HasIndex("ChannelNumberImport")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("PlaylistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
