// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tv7Playlist.Data;

namespace Tv7Playlist.Data.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    partial class PlaylistContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Tv7Playlist.Data.PlaylistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsAvailable");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name");

                    b.Property<string>("NameOverride");

                    b.Property<int>("Position");

                    b.Property<int>("TrackNumber");

                    b.Property<int>("TrackNumberOverride");

                    b.Property<string>("Url");

                    b.Property<string>("UrlOriginal");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TrackNumber")
                        .IsUnique();

                    b.ToTable("PlaylistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
